### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by stevemmarshall** [cancerdatasci/ceres-manuscript#1]
Hi

I'm trying to run the examples you provide and I'm getting this error. I can't find this file anywhere.. Error: './data/raw/hart2014_seed_core_essentials.txt' does not exist in current working directory.

Also saw similar issues running the examples from the ceres R package. Missing bowtie indexes from the zip file that was provided.

thanks
Steve

**Comment by robinmeyers** [comment]
Hi Steve,

Thank you for alerting us of this oversight! It's been resolved now and included in the repo. Please continue to let us know if you have further issues.

Best,
Robin

**Comment by stevemmarshall** [comment]
Hi Robin

Thanks your work on this project and quick fix.

cheers
steve

**Comment by stevemmarshall** [comment]
Hi Robin

Looks like you are missing some ccle_lineage.tsv file as well. 

cheers
steve

**Comment by j-g-b** [comment]
Hi Steve,

Thanks for helping us iron out these kinks. We'll upload asap. 

A link to the hg19 bowtie indices has now been provided in the README for the CERES R package.

Best,
Jordan

**Comment by stevemmarshall** [comment]
Great thanks... There are some efforts like this one by hadley that look really useful for automating/checking when writing code/packages.. https://github.com/r-lib/usethis

**Comment by robinmeyers** [comment]
Hi Steve,

The ccle_lineages file has been checked in as well, but notice both both this and the hart2014 file were moved to 'data/manual/'. Thanks for the tip.

-Robin
